### ISSUE TITLE
Possible mistakes in the doctor_spec.rb and patient_spec.rb files

### ISSUE THREAD

**Issue by mnavoy4** [learn-co-curriculum/ruby-oo-object-relationships-has-many-through-lab#1]

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials so hopefully the issue has been resolved. Note, however, that if you are working in Canvas the changes may not appear right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
